### ISSUE TITLE
[BUG] docs workflow is broken

### ISSUE THREAD

**Issue by jiyoung-an** [ainft-team/ainft-js#260]
### Issue
docs workflow is currently broken in build step. 
The ainft-js requires node engine version ">=16", but workflow engine is "14.12.3".

See: https://github.com/ainft-team/ainft-js/actions/runs/8165531501/job/22322835510

**Comment by platfowner** [comment]
is this issue already resolved? @jiyoung-an

**Comment by jiyoung-an** [comment]
@platfowner yes, i resolved this issue!
